### openAI gym

创建运行环境

In [33]:
import gym

# gym 与 jupyter notebook 有冲突, 调用 render 会挂起
# 本地运行设置为 true
isLocalPlaying = False

env = gym.make('CartPole-v0')

# 设置随机数种子
env.seed(seed=12345)

# 重置环境
observation = env.reset()
print(observation)

if isLocalPlaying:
    env.render()

print(env.action_space)
# output : Discrete(2) (0, 1, ..., n-1) 的离散值
print(env.action_space.n)
print(env.observation_space)

for step in range(100):
    # 抽样动作
    action = env.action_space.sample()

    # 采取动作
    observation, reward, done, info = env.step(action)
    print(observation, reward)
    
    if isLocalPlaying:
        env.render()
    if done:
        print('done')
        break

env.close()

[ 0.0021311  -0.02618807  0.03980482  0.03168933]
Discrete(2)
2
Box(4,)
[ 0.00160734 -0.22185756  0.04043861  0.33666062] 1.0
[-0.00282981 -0.41753096  0.04717182  0.64181647] 1.0
[-0.01118043 -0.2230972   0.06000815  0.36435364] 1.0
[-0.01564238 -0.41901836  0.06729522  0.67533822] 1.0
[-0.02402274 -0.61500775  0.08080199  0.98842674] 1.0
[-0.0363229  -0.81111307  0.10057052  1.30535491] 1.0
[-0.05254516 -0.61739971  0.12667762  1.04577103] 1.0
[-0.06489315 -0.42416601  0.14759304  0.79538671] 1.0
[-0.07337647 -0.62097187  0.16350077  1.13062094] 1.0
[-0.08579591 -0.81781249  0.18611319  1.46979946] 1.0
[-0.10215216 -0.62539055  0.21550918  1.24055294] 1.0
done


### 判断 env 中 action 和 observation 的**维度**,**连续型**和**离散型**

In [37]:
import gym
import numpy as np

def is_tuple(env):
    tuple_space, dict_space = gym.spaces.Tuple, gym.spaces.Dict
    tuple_action = isinstance(env.action_space, (tuple_space, dict_space))
    tuple_obs = isinstance(env.observation_space, (tuple_space, dict_space))
    return tuple_action, tuple_obs

def is_multidimensional(env):
    md_action, md_obs = True, True
    tuple_action, tuple_obs = is_tuple(env)
    if not tuple_action:
        act = env.action_space.sample()
        md_action = isinstance(act, (tuple, list, np.ndarray)) and len(act) > 0
    if not tuple_obs:
        obs = env.observation_space.low if 'low' in dir(env.observation_space) else env.observation_space.sample()
        md_obs = isinstance(obs, (tuple, list, np.ndarray)) and len(obs) > 0
    return md_action, md_obs, tuple_action, tuple_obs

def is_continuous(env, tuple_action, tuple_obs):
    if tuple_action:
        spaces = env.action_space.spaces
        cont_action = all([isinstance(s, gym.spaces.box.Box) for s in spaces])
    else:
        cont_action = isinstance(env.action_space, gym.spaces.box.Box)
        
    if tuple_obs:
        spaces = env.observation_space.spaces
        cont_obs = all([isinstance(s, gym.spaces.box.Box) for s in spaces])
    else:
        cont_obs = isinstance(env.observation_space, gym.spaces.box.Box)
        
    return cont_action, cont_obs

In [50]:
import gym

env = gym.make('CartPole-v0')
# env = gym.make('Taxi-v2')
# env = gym.make('Copy-v0')
md_action, md_obs, tuple_action, tuple_obs = is_multidimensional(env)
print('md_action, md_obs, tuple_action, tuple_obs')
print(md_action, md_obs, tuple_action, tuple_obs)
cont_action, cont_obs = is_continuous(env, tuple_action, tuple_obs)
print('cont_action, cont_obs')
print(cont_action, cont_obs)

env.close()

md_action, md_obs, tuple_action, tuple_obs
False True False False
cont_action, cont_obs
False True
