# Numpy 基础

### 创建 array
---

导入库文件

In [2]:
import numpy as np


创建 array


In [11]:
a = np.array([1, 2, 3])
print(a, a.dtype)

b = np.array([1., 2., 3.])
print(b, b.dtype)

c = np.array([1, 2, 3], dtype=complex)
print(c, c.dtype)


[1 2 3] int64
[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


创建 n 维数组


In [27]:
b = np.array([(1., 2., 3.), (4., 5., 6.)])
print(b)

# 错误示例: (维度不对)
c = np.array([(1, 2), (3, 4, 5)])
print(c, c.shape)


[[1. 2. 3.]
 [4. 5. 6.]]
[(1, 2) (3, 4, 5)] (2,)


快速创建方法


In [32]:
np.zeros((3, 5))

np.ones((2,3,4), dtype=np.int16)

np.empty((2, 3))


array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])