# Numpy 基础

### 创建 array
---

导入库文件

In [1]:
import numpy as np


创建 array


In [2]:
a = np.array([1, 2, 3])
print(a, a.dtype)

b = np.array([1., 2., 3.])
print(b, b.dtype)

c = np.array([1, 2, 3], dtype=complex)
print(c, c.dtype)

print(np.r_[1:6, 6, 6])
print(np.c_[1:6])


[1 2 3] int64
[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128
[1 2 3 4 5 6 6]
[[1]
 [2]
 [3]
 [4]
 [5]]


创建 n 维数组


In [3]:
b = np.array([(1., 2., 3.), (4., 5., 6.)])
print(b)

# 错误示例: (维度不对)
c = np.array([(1, 2), (3, 4, 5)])
print(c, c.shape)


[[1. 2. 3.]
 [4. 5. 6.]]
[(1, 2) (3, 4, 5)] (2,)


快速创建方法


In [4]:
np.zeros((3, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,3,4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
# 结果没有初始化
np.empty((2, 3))


array([[1., 2., 3.],
       [4., 5., 6.]])

生成序列 number


In [7]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10, 30, 5)


array([10, 15, 20, 25])

In [9]:
np.arange(0, 2, 0.3)


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [10]:
np.linspace(0, 2, 9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

1 维转 n 维


In [ ]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
# 错误示例: 维数相乘不相等
np.arange(10).reshape(2, 3)


ValueError: cannot reshape array of size 10 into shape (2,3)

基本操作


In [ ]:
a = np.array([20, 30, 40, 50, 60])
b = np.arange(5)

c = a - b
print(c)

# power
print(b**2)

print(10 * np.sin(a))

print(a < 36)

乘法操作


In [13]:
A = np.array([[1, 1], 
              [0, 1]])
B = np.array([[2, 0], 
              [3, 4]])
# elementwise product
print(A * B)
# matrix product
print(A @ B)
# another matrix product
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


+= 和 *= 等类似操作会改变现有 array


In [14]:
a = np.ones((2, 3))
print(a)
a *= 3
print(a)

b = np.random.random((2, 3))
print(b)
b += a
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[0.42859234 0.13261324 0.03220195]
 [0.89693628 0.88032148 0.99160312]]
[[3.42859234 3.13261324 3.03220195]
 [3.89693628 3.88032148 3.99160312]]


数据类型转换


In [15]:
a = np.ones((2, 3), dtype=np.int)
b = np.random.random((2, 3))
print(a.dtype, b.dtype)

# int -> float
b += a
print(b)

# 错误示例: float -> int
a += b


int64 float64
[[1.51506165 1.79247882 1.30552541]
 [1.53201723 1.55589871 1.74521915]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

ndarray 的一元操作


In [16]:
a = np.random.random((2, 3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

b = np.arange(12).reshape(3, 4)
print(b)
print(b.sum(axis = 0))
print(b.sum(axis = 1))
# 每行的累计值
print(b.cumsum(axis = 1))

[[0.12949135 0.29624386 0.86730455]
 [0.26157833 0.32205075 0.49058799]]
2.3672568377037355
0.12949135280032598
0.8673045524915247
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


通用方法,如: 

sin, cos, exp, all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where


In [17]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

C = np.array([2., -1., 3.])
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 5.]


array 的取值,切片和迭代


In [18]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[1:6])
print(a[:-1])

for i in a:
    print(i * 3)

[  0   1   8  27  64 125 216 343 512 729]
8
[  1   8  27  64 125]
[  0   1   8  27  64 125 216 343 512]
0
3
24
81
192
375
648
1029
1536
2187


多维度 array 取值


In [19]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=np.int)
print(b)
print(b[2, 3])
print(b[:5, 1])
print(b[:, 1])
print(b[1:3, :])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


点操作 (`...`) 代表省略的冒号.如: `x` 为 5 维数组, 则:
- `x[1, 2, ...]` = `x[1, 2, :, :, :]`
- `x[..., 3]` = `x[:, :, :, :, 3]`
- `x[4, ..., 5, :]` = `x[4, :, :, 5, :]`


In [20]:
c = np.fromfunction(lambda x, y, z: 10**x + y + 2*z, (2, 2, 3), dtype=np.int)
print(c)
print(c[1, ...])
print(c[..., 2])

for row in c:
    print('row: ', row)

for element in c.flat:
    print('element: ', element)

[[[ 1  3  5]
  [ 2  4  6]]

 [[10 12 14]
  [11 13 15]]]
[[10 12 14]
 [11 13 15]]
[[ 5  6]
 [14 15]]
row:  [[1 3 5]
 [2 4 6]]
row:  [[10 12 14]
 [11 13 15]]
element:  1
element:  3
element:  5
element:  2
element:  4
element:  6
element:  10
element:  12
element:  14
element:  11
element:  13
element:  15


维度控制


In [21]:
a = np.array([[0, 1, 2, 3, 4], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14]], order='F')
print(a, a.shape)

# matrix.flatten : returns a similar output matrix but always a copy
# matrix.flat : a flat iterator on the array.
# numpy.ravel : related function which returns an ndarray
print(a.flatten())
print(a.ravel())

b = a.reshape(5, 3)
print(b, b.shape)

c = a.T
print(c, c.shape)

# 与 array 的 order 有关, 如果是 Fortran 风格的 array ,则与 reshape 的结果不同
# 且会改变原 array
a.resize(5, 3)
print(a, a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] (5, 3)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)
[[ 0 11  8]
 [ 5  2 13]
 [10  7  4]
 [ 1 12  9]
 [ 6  3 14]] (5, 3)


array 的连接方法


In [22]:
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.column_stack((a, b)))
print(np.row_stack((a, b)))


[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1 2]
 [1 2]
 [1 2]]
[[1 1 1]
 [2 2 2]]


array 的分离方法

In [50]:

a = np.arange(18).reshape(3, 6)
print(a)
# 按份数分
print(np.hsplit(a, 3))
# 按分割线分
print(np.hsplit(a, (1, 3)))
print(np.vsplit(a, 3))
print(np.vsplit(a, (2, 5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0],
       [ 6],
       [12]]), array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]]), array([], shape=(0, 6), dtype=int64)]
